name: Publish Latest Version

on:
  push:
    tags:
      - v4.*

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          check-latest: true
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      - run: npm publish --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
